name: kittygram
services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -U "$${POSTGRES_USER}" -d "$${POSTGRES_DB}"']
      interval: 5s
      timeout: 5s
      retries: 30
  backend:
    image: ${DOCKERHUB_USERNAME:-mezhnun}/kittygram_backend:${IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    image: ${DOCKERHUB_USERNAME:-mezhnun}/kittygram_frontend:${IMAGE_TAG:-latest}
    restart: 'no'
    command: [sh, -c, 'cp -a /app/build/. /static/']
    volumes:
      - static:/static
  gateway:
    image: ${DOCKERHUB_USERNAME:-mezhnun}/kittygram_gateway:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - '${GATEWAY_PORT:-9000}:80'
    volumes:
      - static:/static:ro
      - media:/media:ro
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_completed_successfully
volumes:
  pg_data:
  static:
  media:
